### PR TITLE
Add option to exclude default things

### PR DESCRIPTION
**Pull request by bewee**
This proposes adding an option to exclude the default virtual things, and points somewhat in a similar direction as #56

### CODE REVIEW

**Comment by benfrancis** [comment]
@bewee Just a quick note to say thank you very much for submitting this and your other PRs on the virtual things adapter repo. This adapter is currently lacking a maintainer but I'm going to try to find a reviewer to review these patches.

**Comment by bewee** [comment]
@benfrancis Alright, don't stress yourself!
Btw if still needed and if you are interested, I could imagine maintaining this repo :) (after review of the PRs)

**Review by tim-hellhake — APPROVED** [review]
I like that! The default devices always crowded my new devices list.

**Comment by tim-hellhake** [comment]
@benfrancis I can't press the merge button so it's up to you :smile:

**Comment by benfrancis** [comment]
Thanks @tim-hellhake, I've added you as a peer with committer rights so you can land patches until we assign a new owner/peer for this module.

**Pull request merged**
